CREATE TABLE dbo.person (
	[id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[first_name] VARCHAR(80) NOT NULL,
	[last_name] VARCHAR(80) NOT NULL,
	[address] VARCHAR(100) NOT NULL,
	[gender] VARCHAR(6) NOT NULL,
	CONSTRAINT PK_person PRIMARY KEY ([id])
);